services:
  core:
    replicas: 1
    image: 
      name: toggly/core
      tag: latest
    resources: {}
    service:
      type: ClusterIP
      port: 80
    ingress:
      enabled: true
      annotations: 
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
      hosts:
        - host: api.toggly.me
          paths: 
          - /rest-api
      tls: 
      - hosts:
        - toggly.me
        secretName: toggly-me-tls  

secrets:
  dbconnection: mongodb://localhost/toggly
  dbname: toggly
  sessionskey: {{ randAlphaNum 32 }}

