apiVersion: v1
kind: Secret
metadata:
  name: test-secret
data:
  dbconnection: {{ b64enc .Values.secrets.dbconnection }}
  dbname: {{ b64enc .Values.secrets.dbname }}
  sessionskey: {{ b64enc .Values.secrets.sessionskey }}